groupthinking-patch-3
 # To get started with Dependabot version updates, you'll need to specify which
 master
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
groupthinking-patch-3
  - package-ecosystem: "" # See documentation for possible values

 groupthinking-patch-2
  - package-ecosystem: "" # See documentation for possible values

  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
master
master
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
