name: Python CI

# CI workflow for linting and testing Python code
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Lint with black
        run: black --check .
      - name: Lint with flake8
        run: flake8 . || echo "Flake8 found issues but continuing CI"
        continue-on-error: true
      - name: Run tests with coverage
        run: pytest --cov=. || echo "Tests failed but continuing CI"
        continue-on-error: true

  actions:
    runs-on: ubuntu-latest
    needs: lint-test
    if: always()
    steps:
      - name: Check lint-test results
        run: |
          echo "Lint/test jobs completed"